; --------------------------------------------------------------------------------------------------------------------- ;
; C64 Colour RAM - Only the low nibble of each Color RAM location is connected
;                  A WRITE to the high nybble has no effect
;                  A READ  of the high nybble usually returns random values and should be masked out
; --------------------------------------------------------------------------------------------------------------------- ;
VICCOL                      = COLORLOC           ; $d800 - $dbff - VIC color nibbles
VICCOL_PAGE_0                 = COLORLOC + $0000 ; $d800 - $d8ff
VICCOL_PAGE_1                 = COLORLOC + $0100 ; $d900 - $d9ff
VICCOL_PAGE_2                 = COLORLOC + $0200 ; $da00 - $daff
VICCOL_PAGE_3                 = COLORLOC + $0300 ; $db00 - $dbff
                              

VICCOL_MASK                 = %00001111          ; Only the lower 4 bits are connected - the upper 4 bits should be masked out
VICCOL_MCM_ON               = %00001000          ;       set bit3 for MCM colors - colors reduced to $00-$07
VICCOL_MCM_OFF              = ~VICCOL_MCM_ON     ; 
; --------------------------------------------------------------------------------------------------------------------- ;
COLORAM                     = COLORLOC           ; $d800 - $dbff
COLORAM_PAGE_0                = VICCOL_PAGE_0    ; $d800 - $d8ff
COLORAM_PAGE_1                = VICCOL_PAGE_1    ; $d900 - $d9ff
COLORAM_PAGE_2                = VICCOL_PAGE_2    ; $da00 - $daff
COLORAM_PAGE_3                = VICCOL_PAGE_3    ; $db00 - $dbff
                              
COLORAM_MCM_ON                = VICCOL_MCM_ON    ; set bit3 for MCM colors - colors reduced to $00-$07
COLORAM_MCM_OFF               = VICCOL_MCM_OFF   ; 
; --------------------------------------------------------------------------------------------------------------------- ;
; COLOR constants
; --------------------------------------------------------------------------------------------------------------------- ;
; Simple colors
; --------------------------------------------------------------------------------------------------------------------- ;
BLACK                       = $00 ; 
WHITE                       = $01 ; 
RED                         = $02 ; 
CYAN                        = $03 ; 
PURPLE                      = $04 ; 
GREEN                       = $05 ; 
BLUE                        = $06 ; 
YELLOW                      = $07 ; 
ORANGE                      = $08 ; 
BROWN                       = $09 ; 
LT_RED                      = $0a ; 
DK_GREY                     = $0b ; 
GREY                        = $0c ; 
LT_GREEN                    = $0d ; 
LT_BLUE                     = $0e ; 
LT_GREY                     = $0f ; 
; --------------------------------------------------------------------------------------------------------------------- ;
; HiRes color combinations
; --------------------------------------------------------------------------------------------------------------------- ;
HR_BLACK_BLACK              = $00 ; 
HR_BLACK_WHITE              = $01 ; 
HR_BLACK_RED                = $02 ; 
HR_BLACK_CYAN               = $03 ; 
HR_BLACK_PURPLE             = $04 ; 
HR_BLACK_GREEN              = $05 ; 
HR_BLACK_BLUE               = $06 ; 
HR_BLACK_YELLOW             = $07 ; 
HR_BLACK_ORANGE             = $08 ; 
HR_BLACK_BROWN              = $09 ; 
HR_BLACK_LT_RED             = $0a ; 
HR_BLACK_DK_GREY            = $0b ; 
HR_BLACK_GREY               = $0c ; 
HR_BLACK_LT_GREEN           = $0d ; 
HR_BLACK_LT_BLUE            = $0e ; 
HR_BLACK_LT_GREY            = $0f ; 
; --------------------------------------------------------------------------------------------------------------------- ;
HR_WHITE_BLACK              = $10 ; 
HR_WHITE_WHITE              = $11 ; 
HR_WHITE_RED                = $12 ; 
HR_WHITE_CYAN               = $13 ; 
HR_WHITE_PURPLE             = $14 ; 
HR_WHITE_GREEN              = $15 ; 
HR_WHITE_BLUE               = $16 ; 
HR_WHITE_YELLOW             = $17 ; 
HR_WHITE_ORANGE             = $18 ; 
HR_WHITE_BROWN              = $19 ; 
HR_WHITE_LT_RED             = $1a ; 
HR_WHITE_DK_GREY            = $1b ; 
HR_WHITE_GREY               = $1c ; 
HR_WHITE_LT_GREEN           = $1d ; 
HR_WHITE_LT_BLUE            = $1e ; 
HR_WHITE_LT_GREY            = $1f ; 
; --------------------------------------------------------------------------------------------------------------------- ;
HR_RED_BLACK                = $20 ; 
HR_RED_WHITE                = $21 ; 
HR_RED_RED                  = $22 ; 
HR_RED_CYAN                 = $23 ; 
HR_RED_PURPLE               = $24 ; 
HR_RED_GREEN                = $25 ; 
HR_RED_BLUE                 = $26 ; 
HR_RED_YELLOW               = $27 ; 
HR_RED_ORANGE               = $28 ; 
HR_RED_BROWN                = $29 ; 
HR_RED_LT_RED               = $2a ; 
HR_RED_DK_GREY              = $2b ; 
HR_RED_GREY                 = $2c ; 
HR_RED_LT_GREEN             = $2d ; 
HR_RED_LT_BLUE              = $2e ; 
HR_RED_LT_GREY              = $2f ; 
; --------------------------------------------------------------------------------------------------------------------- ;
HR_CYAN_BLACK               = $30 ; 
HR_CYAN_WHITE               = $31 ; 
HR_CYAN_RED                 = $32 ; 
HR_CYAN_CYAN                = $33 ; 
HR_CYAN_PURPLE              = $34 ; 
HR_CYAN_GREEN               = $35 ; 
HR_CYAN_BLUE                = $36 ; 
HR_CYAN_YELLOW              = $37 ; 
HR_CYAN_ORANGE              = $38 ; 
HR_CYAN_BROWN               = $39 ; 
HR_CYAN_LT_RED              = $3a ; 
HR_CYAN_DK_GREY             = $3b ; 
HR_CYAN_GREY                = $3c ; 
HR_CYAN_LT_GREEN            = $3d ; 
HR_CYAN_LT_BLUE             = $3e ; 
HR_CYAN_LT_GREY             = $3f ; 
; --------------------------------------------------------------------------------------------------------------------- ;
HR_PURPLE_BLACK             = $40 ; 
HR_PURPLE_WHITE             = $41 ; 
HR_PURPLE_RED               = $42 ; 
HR_PURPLE_CYAN              = $43 ; 
HR_PURPLE_PURPLE            = $44 ; 
HR_PURPLE_GREEN             = $45 ; 
HR_PURPLE_BLUE              = $46 ; 
HR_PURPLE_YELLOW            = $47 ; 
HR_PURPLE_ORANGE            = $48 ; 
HR_PURPLE_BROWN             = $49 ; 
HR_PURPLE_LT_RED            = $4a ; 
HR_PURPLE_DK_GREY           = $4b ; 
HR_PURPLE_GREY              = $4c ; 
HR_PURPLE_LT_GREEN          = $4d ; 
HR_PURPLE_LT_BLUE           = $4e ; 
HR_PURPLE_LT_GREY           = $4f ; 
; --------------------------------------------------------------------------------------------------------------------- ;
HR_GREEN_BLACK              = $50 ; 
HR_GREEN_WHITE              = $51 ; 
HR_GREEN_RED                = $52 ; 
HR_GREEN_CYAN               = $53 ; 
HR_GREEN_PURPLE             = $54 ; 
HR_GREEN_GREEN              = $55 ; 
HR_GREEN_BLUE               = $56 ; 
HR_GREEN_YELLOW             = $57 ; 
HR_GREEN_ORANGE             = $58 ; 
HR_GREEN_BROWN              = $59 ; 
HR_GREEN_LT_RED             = $5a ; 
HR_GREEN_DK_GREY            = $5b ; 
HR_GREEN_GREY               = $5c ; 
HR_GREEN_LT_GREEN           = $5d ; 
HR_GREEN_LT_BLUE            = $5e ; 
HR_GREEN_LT_GREY            = $5f ; 
; --------------------------------------------------------------------------------------------------------------------- ;
HR_BLUE_BLACK               = $60 ; 
HR_BLUE_WHITE               = $61 ; 
HR_BLUE_RED                 = $62 ; 
HR_BLUE_CYAN                = $63 ; 
HR_BLUE_PURPLE              = $64 ; 
HR_BLUE_GREEN               = $65 ; 
HR_BLUE_BLUE                = $66 ; 
HR_BLUE_YELLOW              = $67 ; 
HR_BLUE_ORANGE              = $68 ; 
HR_BLUE_BROWN               = $69 ; 
HR_BLUE_LT_RED              = $6a ; 
HR_BLUE_DK_GREY             = $6b ; 
HR_BLUE_GREY                = $6c ; 
HR_BLUE_LT_GREEN            = $6d ; 
HR_BLUE_LT_BLUE             = $6e ; 
HR_BLUE_LT_GREY             = $6f ; 
; --------------------------------------------------------------------------------------------------------------------- ;
HR_YELLOW_BLACK             = $70 ; 
HR_YELLOW_WHITE             = $71 ; 
HR_YELLOW_RED               = $72 ; 
HR_YELLOW_CYAN              = $73 ; 
HR_YELLOW_PURPLE            = $74 ; 
HR_YELLOW_GREEN             = $75 ; 
HR_YELLOW_BLUE              = $76 ; 
HR_YELLOW_YELLOW            = $77 ; 
HR_YELLOW_ORANGE            = $78 ; 
HR_YELLOW_BROWN             = $79 ; 
HR_YELLOW_LT_RED            = $7a ; 
HR_YELLOW_DK_GREY           = $7b ; 
HR_YELLOW_GREY              = $7c ; 
HR_YELLOW_LT_GREEN          = $7d ; 
HR_YELLOW_LT_BLUE           = $7e ; 
HR_YELLOW_LT_GREY           = $7f ; 
; --------------------------------------------------------------------------------------------------------------------- ;
HR_ORANGE_BLACK             = $80 ; 
HR_ORANGE_WHITE             = $81 ; 
HR_ORANGE_RED               = $82 ; 
HR_ORANGE_CYAN              = $83 ; 
HR_ORANGE_PURPLE            = $84 ; 
HR_ORANGE_GREEN             = $85 ; 
HR_ORANGE_BLUE              = $86 ; 
HR_ORANGE_YELLOW            = $87 ; 
HR_ORANGE_ORANGE            = $88 ; 
HR_ORANGE_BROWN             = $89 ; 
HR_ORANGE_LT_RED            = $8a ; 
HR_ORANGE_DK_GREY           = $8b ; 
HR_ORANGE_GREY              = $8c ; 
HR_ORANGE_LT_GREEN          = $8d ; 
HR_ORANGE_LT_BLUE           = $8e ; 
HR_ORANGE_LT_GREY           = $8f ; 
; --------------------------------------------------------------------------------------------------------------------- ;
HR_BROWN_BLACK              = $90 ; 
HR_BROWN_WHITE              = $91 ; 
HR_BROWN_RED                = $92 ; 
HR_BROWN_CYAN               = $93 ; 
HR_BROWN_PURPLE             = $94 ; 
HR_BROWN_GREEN              = $95 ; 
HR_BROWN_BLUE               = $96 ; 
HR_BROWN_YELLOW             = $97 ; 
HR_BROWN_ORANGE             = $98 ; 
HR_BROWN_BROWN              = $99 ; 
HR_BROWN_LT_RED             = $9a ; 
HR_BROWN_DK_GREY            = $9b ; 
HR_BROWN_GREY               = $9c ; 
HR_BROWN_LT_GREEN           = $9d ; 
HR_BROWN_LT_BLUE            = $9e ; 
HR_BROWN_LT_GREY            = $9f ; 
; --------------------------------------------------------------------------------------------------------------------- ;
HR_LT_RED_BLACK              = $a0 ; 
HR_LT_RED_WHITE              = $a1 ; 
HR_LT_RED_RED                = $a2 ; 
HR_LT_RED_CYAN               = $a3 ; 
HR_LT_RED_PURPLE             = $a4 ; 
HR_LT_RED_GREEN              = $a5 ; 
HR_LT_RED_BLUE               = $a6 ; 
HR_LT_RED_YELLOW             = $a7 ; 
HR_LT_RED_ORANGE             = $a8 ; 
HR_LT_RED_BROWN              = $a9 ; 
HR_LT_RED_LT_RED             = $aa ; 
HR_LT_RED_DK_GREY            = $ab ; 
HR_LT_RED_GREY               = $ac ; 
HR_LT_RED_LT_GREEN           = $ad ; 
HR_LT_RED_LT_BLUE            = $ae ; 
HR_LT_RED_LT_GREY            = $af ; 
; --------------------------------------------------------------------------------------------------------------------- ;
HR_DK_GREY_BLACK            = $b0 ; 
HR_DK_GREY_WHITE            = $b1 ; 
HR_DK_GREY_RED              = $b2 ; 
HR_DK_GREY_CYAN             = $b3 ; 
HR_DK_GREY_PURPLE           = $b4 ; 
HR_DK_GREY_GREEN            = $b5 ; 
HR_DK_GREY_BLUE             = $b6 ; 
HR_DK_GREY_YELLOW           = $b7 ; 
HR_DK_GREY_ORANGE           = $b8 ; 
HR_DK_GREY_BROWN            = $b9 ; 
HR_DK_GREY_LT_RED           = $ba ; 
HR_DK_GREY_DK_GREY          = $bb ; 
HR_DK_GREY_GREY             = $bc ; 
HR_DK_GREY_LT_GREEN         = $bd ; 
HR_DK_GREY_LT_BLUE          = $be ; 
HR_DK_GREY_LT_GREY          = $bf ; 
; --------------------------------------------------------------------------------------------------------------------- ;
HR_GREY_BLACK               = $c0 ; 
HR_GREY_WHITE               = $c1 ; 
HR_GREY_RED                 = $c2 ; 
HR_GREY_CYAN                = $c3 ; 
HR_GREY_PURPLE              = $c4 ; 
HR_GREY_GREEN               = $c5 ; 
HR_GREY_BLUE                = $c6 ; 
HR_GREY_YELLOW              = $c7 ; 
HR_GREY_ORANGE              = $c8 ; 
HR_GREY_BROWN               = $c9 ; 
HR_GREY_LT_RED              = $ca ; 
HR_GREY_DK_GREY             = $cb ; 
HR_GREY_GREY                = $cc ; 
HR_GREY_LT_GREEN            = $cd ; 
HR_GREY_LT_BLUE             = $ce ; 
HR_GREY_LT_GREY             = $cf ; 
; --------------------------------------------------------------------------------------------------------------------- ;
HR_LT_GREEN_BLACK           = $d0 ; 
HR_LT_GREEN_WHITE           = $d1 ; 
HR_LT_GREEN_RED             = $d2 ; 
HR_LT_GREEN_CYAN            = $d3 ; 
HR_LT_GREEN_PURPLE          = $d4 ; 
HR_LT_GREEN_GREEN           = $d5 ; 
HR_LT_GREEN_BLUE            = $d6 ; 
HR_LT_GREEN_YELLOW          = $d7 ; 
HR_LT_GREEN_ORANGE          = $d8 ; 
HR_LT_GREEN_BROWN           = $d9 ; 
HR_LT_GREEN_LT_RED          = $da ; 
HR_LT_GREEN_DK_GREY         = $db ; 
HR_LT_GREEN_GREY            = $dc ; 
HR_LT_GREEN_LT_GREEN        = $dd ; 
HR_LT_GREEN_LT_BLUE         = $de ; 
HR_LT_GREEN_LT_GREY         = $df ; 
; --------------------------------------------------------------------------------------------------------------------- ;
HR_LT_BLUE_BLACK            = $e0 ; 
HR_LT_BLUE_WHITE            = $e1 ; 
HR_LT_BLUE_RED              = $e2 ; 
HR_LT_BLUE_CYAN             = $e3 ; 
HR_LT_BLUE_PURPLE           = $e4 ; 
HR_LT_BLUE_GREEN            = $e5 ; 
HR_LT_BLUE_BLUE             = $e6 ; 
HR_LT_BLUE_YELLOW           = $e7 ; 
HR_LT_BLUE_ORANGE           = $e8 ; 
HR_LT_BLUE_BROWN            = $e9 ; 
HR_LT_BLUE_LT_RED           = $ea ; 
HR_LT_BLUE_DK_GREY          = $eb ; 
HR_LT_BLUE_GREY             = $ec ; 
HR_LT_BLUE_LT_GREEN         = $ed ; 
HR_LT_BLUE_LT_BLUE          = $ee ; 
HR_LT_BLUE_LT_GREY          = $ef ; 
; --------------------------------------------------------------------------------------------------------------------- ;
HR_LT_GREY_BLACK            = $f0 ; 
HR_LT_GREY_WHITE            = $f1 ; 
HR_LT_GREY_RED              = $f2 ; 
HR_LT_GREY_CYAN             = $f3 ; 
HR_LT_GREY_PURPLE           = $f4 ; 
HR_LT_GREY_GREEN            = $f5 ; 
HR_LT_GREY_BLUE             = $f6 ; 
HR_LT_GREY_YELLOW           = $f7 ; 
HR_LT_GREY_ORANGE           = $f8 ; 
HR_LT_GREY_BROWN            = $f9 ; 
HR_LT_GREY_LT_RED           = $fa ; 
HR_LT_GREY_DK_GREY          = $fb ; 
HR_LT_GREY_GREY             = $fc ; 
HR_LT_GREY_LT_GREEN         = $fd ; 
HR_LT_GREY_LT_BLUE          = $fe ; 
HR_LT_GREY_LT_GREY          = $ff ; 
; --------------------------------------------------------------------------------------------------------------------- ;
